# Generated by Django 4.2.5 on 2024-01-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAdministrativa',
            fields=[
                ('id_atividade', models.IntegerField(primary_key=True, serialize=False)),
                ('carga_horaria_semanal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id_demanda', models.IntegerField(primary_key=True, serialize=False)),
                ('ano_fk', models.IntegerField()),
                ('semestre_fk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id_matriz', models.AutoField(primary_key=True, serialize=False)),
                ('ano_matriz', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelDeEnsino',
            fields=[
                ('id_nivel', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_nivel', models.CharField(max_length=40)),
                ('turno_de_funcionamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome_professor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('primary_key', models.DateTimeField(default=None, verbose_name='primary_key')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaModulo',
            fields=[
                ('codigo_turma', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.CharField(default=None, verbose_name='primary_key')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.demanda')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('observacao', models.CharField(max_length=255)),
                ('carga_horario_semestral', models.IntegerField()),
                ('carga_horario_semanal', models.IntegerField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.turmamodulo')),
            ],
        ),
        migrations.AddField(
            model_name='demanda',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.semestre'),
        ),
        migrations.AddField(
            model_name='curso',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.matriz'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.niveldeensino'),
        ),
        migrations.CreateModel(
            name='AtividadeAdministrativaProfessor',
            fields=[
                ('id_atividade_professor', models.IntegerField(primary_key=True, serialize=False)),
                ('date_inicio', models.DateField()),
                ('date_fim', models.DateField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.atividadeadministrativa')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.professor')),
            ],
        ),
    ]
